### ISSUE TITLE
Errors running an empty project with the plugin enabled

### ISSUE THREAD

**Issue by DavidGasku** [coppolaemilio/dialogic#1478]
## The problem

**Describe the bug**
```
E 0:00:00:0608   load_source_code: Attempt to open script 'res://addons/dialogic/Events/Text/node_input_handler.gd' resulted in error 'File not found'.
E 0:00:00:0610   load_source_code: Attempt to open script 'res://addons/dialogic/Events/Character/node_portrait_position.gd' resulted in error 'File not found'.
E 0:00:00:0702   DialogicGameHandler.gd:270 @ get_subsystem(): Node not found: "Portraits" (relative to "/root/Dialogic").

```
**To Reproduce**
Just activate the plugin and start the program

**System (please complete the following information):**
Ubuntu 22.04
Godot version: v4.0.stable.official [92bee43ad]
Dialogic version: 2.0-Alpha-6 (for Godot 4.0 stable)

**Comment by Jowan-Spooner** [comment]
I think these errors are fixed now on main, need to test it again in an empty project though.

**Comment by Bricklou** [comment]
Hi ! I just tried with godot 4.0.1 and the commit [8332451](https://github.com/coppolaemilio/dialogic/commit/8332451efa37a7224b501bad0349d2d9b42b47ea) on my project and i still get this error.

```
E 0:00:00:0655   DialogicGameHandler.gd:215 @ get_subsystem(): Node not found: "Portraits" (relative to "/root/Dialogic").
  <Erreur C++>   Method/function failed. Returning: nullptr
  <Source C++>   scene/main/node.cpp:1364 @ get_node()
  <Pile des appels>DialogicGameHandler.gd:215 @ get_subsystem()
                 subsystem_text.gd:202 @ collect_text_effects()
                 subsystem_text.gd:268 @ _ready()
                 DialogicGameHandler.gd:223 @ add_subsytsem()
                 DialogicGameHandler.gd:203 @ collect_subsystems()
                 DialogicGameHandler.gd:51 @ _ready()
```

**Comment by vmedea** [comment]
ive noticed the same; it looks like an initialization ordering issue: this happens because in `collect_text_effects` it adds the effect `{ "command": "portrait", "subsystem": "Portraits", "method": "text_effect_portrait" }` which relies on the "Portraits" subsystem already being loaded, while it isn't.

**Comment by Jowan-Spooner** [comment]
This has not happened to me for quite some time, so I will close this.
A new issue can be opened if something similar happens again
