### ISSUE TITLE
Set value node not updating values for the current run

### ISSUE THREAD

**Issue by arnaudvergnet** [coppolaemilio/dialogic#79]
* Dialogic version: rc_1.0, commit 853f991d8089777b9aff2607310c7251c04086da

# Summary

When using `Set Value` node to change a variable definition, it only takes effect on the next run.

![Screenshot_20210315_174354](https://user-images.githubusercontent.com/80701113/111189106-09ce7700-85b6-11eb-8d0c-58502c50db2c.png)

For example, in the above screenshot, if the initial value for `test_value` is 1 (set in the definitions tab)), then the if will be triggered, even with the `Set Value` node. If I check the definitions tab after the run, `test_value` is 0. If I run again, the if is not triggered as expected.

The bug might also come from the `if` node not reading the updated value, I didn't know how to test that. 

# The problem

## What is the current behavior?

`Set Value` nodes updated values can only be used in subsequent runs.

## What is the expected correct behavior?

`Set Value` nodes should update the value to be used in the current timeline, in the current run.
Maybe this is the correct behavior, but if it is the case it should be documented.

# Solutions

## Workaround

In [`dialog_node.gd`, `event_handler` function, `condition` branch](https://github.com/coppolaemilio/dialogic/blob/853f991d8089777b9aff2607310c7251c04086da/addons/dialogic/Nodes/dialog_node.gd#L446), I added the line `self.load_config_files()` at the beginning of the branch to force definitions refresh. I haven't tested everything so I don't know if it breaks other stuff, but at least it fixes my issues with if statements

## Possible fixes

Currently, definitions are only parsed at the beginning of the dialog. They should be kept in sync, by parsing again the definitions before using them, or by updating them after a change.

Thanks for this beautiful plugin, keep up the good work!

**Comment by coppolaemilio** [comment]
Yes! This one is realted to https://github.com/coppolaemilio/dialogic/issues/76
I'll get it fix before the official 1.0 release is done 👍

**Comment by arnaudvergnet** [comment]
Thanks! I'll try to work around this issue for now. Do you have an idea when the 1.0 release will be out?

**Comment by arnaudvergnet** [comment]
After a bit of testing, seems that the `if` node is the culprit. I did a simple test: set the value to 1, emit a signal, set the value to 0, emit a signal. In the signal callback, I simply print the value with `Dialogic.get_var("test_value")`, and the printed value is correct.

![Screenshot_20210315_223130](https://user-images.githubusercontent.com/80701113/111224018-339b9400-85de-11eb-804a-dfc2f1b08812.png)

The log:
```
before
[{config:[ConfigFile:1910], name:test_value, section:1615828940-648, type:0}]
1
[D] Current Event: {definition:1615828940-648, set_value:0}
[D] Current Event: {emit_signal:after}
[!] Emitting signal: dialogic_signal(after)
after
[{config:[ConfigFile:1913], name:test_value, section:1615828940-648, type:0}]
0
```

Using this simple main script:

```gdscript
func _ready():
	var new_dialog = Dialogic.start('timeline1')
	add_child(new_dialog)
	new_dialog.connect("dialogic_signal", self, "_on_Dialogic_signal_received")

func _on_Dialogic_signal_received(value: String):
	print(value)
	print(Dialogic.get_var("test_value"))
```

**Comment by arnaudvergnet** [comment]
Found a workaround:

In [`dialog_node.gd`, `event_handler` function, `condition` branch](https://github.com/coppolaemilio/dialogic/blob/853f991d8089777b9aff2607310c7251c04086da/addons/dialogic/Nodes/dialog_node.gd#L446), I added the line `self.load_config_files()` at the beginning of the branch to force definitions refresh. I haven't tested everything so I don't know if it breaks other stuff, but at least it fixes my issues with if statements

**Comment by coppolaemilio** [comment]
That's great! I'll test it out and see if I can push the fix to `main`. I'll be pushing a "runtime" fix so that variables reset when the game closes, so it will probably be pushed with that as well

Thanks!

**Comment by coppolaemilio** [comment]
@arnaudvergnet I pushed a commit with your `load_config_files()` fix and definition variables now reset from session to session. If you would like to save a game you have to provide the `saving_id` variable with the `running_id` from the previous session. I'll write a better tutorial/description on the documentation later on :) 

Please confirm if this commit fixes your issues and thanks again for reporting!

**Comment by arnaudvergnet** [comment]
@coppolaemilio I have errors when pulling the latest change:
![Screenshot_20210316_084836](https://user-images.githubusercontent.com/80701113/111273698-68d2d100-8634-11eb-90b2-8178a3b7f12b.png)

When opening dialogic.gd

![Screenshot_20210316_084906](https://user-images.githubusercontent.com/80701113/111273743-78eab080-8634-11eb-83a2-c9bb436b44f0.png)


When opening DialogicUtil.gd

![Screenshot_20210316_084933](https://user-images.githubusercontent.com/80701113/111273801-8a33bd00-8634-11eb-89e6-bb09245234f6.png)

When opening DialogicSingleton.gd

![Screenshot_20210316_085001](https://user-images.githubusercontent.com/80701113/111273844-99b30600-8634-11eb-8b18-d58064a6df1c.png)

**Comment by coppolaemilio** [comment]
I pushed a new update with a small fix, but for the errors that you are showing me it seems like you did not replace all the changes properly. Try removing the `/addons/dialogic` directory and replacing it with a fresh copy from `main`

**Comment by arnaudvergnet** [comment]
I tried creating a new empty project from a fresh git clone/copy from main, and I still have these errors. Using Godot v3.2.3.stable. I can't even enable the plugin because of this.

**Comment by coppolaemilio** [comment]
I was able to reproduce the issue and I'm working on a fix right now

**Comment by coppolaemilio** [comment]
@arnaudvergnet pushed new changes, can you try again? https://github.com/coppolaemilio/dialogic/commit/6adb0e39e4cba8dd87f6ec4dd9faebcbd87184e3

**Comment by arnaudvergnet** [comment]
Everything seems fixed now! Thanks, I will close this issue

**Comment by coppolaemilio** [comment]
thank you for your help!
